### ISSUE TITLE
API key definition

### ISSUE THREAD

**Issue by Mubramaj** [chrsmrtn-/daskeyboard-applet--jenkins#12]
When setting the API key I can see that the help is:

`https://username:token@jenkins.company.com`

Is it not `https://token@jenkins.company.com instead` ?

I am trying to test it locally so I did:

`http://mytoken@localhost:8080`

Is this correct?

**Comment by chrsmrtn-** [comment]
No, the Jenkins API does not use bearer tokens as expected by the q dashboard framework. So this isn't an "Api key" as we've seen in other plugins that interact with websites.  Instead they allow users to generate "tokens" which are really alternative passwords as you will both need the username and token to still login. To login to a personally hosted jenkins server we need three bits of information.

- Username
- Password (preferably a "token" which is really an alternative password)
- Url and port of the personally hosted jenkins site

I've opted to use a formatted string to receive the information. While this looks like a connection uri with user@hostname, it's a little different.  If there are future plans to users to provide the above three bits of information rather than an "Api key" it will greatly improve the usability of this plugin and any plugin that connects to a personally hosted service.

**Comment by Mubramaj** [comment]
Ok I got it. Thank you. I just added a link to a Jenkins documentation to give to the user more info about setting up the api tokens. I am creating a pull request to your repo. Meanwhile I am going to deploy your Applet right now.

**Comment by chrsmrtn-** [comment]
Okay, i'll close this. Thanks soo much for taking a look at this! Super excited to have the app in the store
